version: '2'

services:
  dev:
    image: node:argon
    working_dir: /usr/src/app
    ports:
        - 8080
    depends_on:
        - mongo
        - redis
    volumes:
        - .:/usr/src/app
    command: npm start
    env_file: .env
    environment:
        - NODE_ENV=development
        - VIRTUAL_HOST=developer.turbasen.privat
        - VIRTUAL_PORT=8080
        - MONGO_DB=test
        - APP_ADMINS=Starefossen,Foo,Bar
        - APP_SECRET=foobar

  redis:
    image: redis:3

  mongo:
    image: mongo:3
