version: '2'

services:
  dev:
    image: node:argon
    network_mode: 'bridge'
    working_dir: /usr/src/app
    ports:
        - 8080
    depends_on:
        - mongo
        - redis
    links:
        - mongo
        - redis
    volumes:
        - .:/usr/src/app
    command: npm start
    env_file: .env
    environment:
        - NODE_ENV=development
        - VIRTUAL_HOST=developer.turbasen.privat
        - VIRTUAL_PORT=8080
        - APP_SECRET=not-a-secret
        - APP_ADMINS=Starefossen,kvikshaug

  redis:
    image: redis:3
    network_mode: 'bridge'

  mongo:
    image: mongo:3
    network_mode: 'bridge'
