version: '2'

services:
  node:
    image: node:argon
    network_mode: 'bridge'
    working_dir: /usr/src/app
    ports:
      - "8080"
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    volumes:
      - .:/usr/src/app
    command: npm start
    env_file: .env
    environment:
      - NODE_ENV=development
      - NPM_CONFIG_LOGLEVEL=silent
      - NPM_CONFIG_PROGRESS=false
      - NPM_CONFIG_SPIN=false
      - VIRTUAL_HOST=developer.nasjonalturbase.local
      - VIRTUAL_PORT=8080
      - APP_SECRET=not-a-secret
      - APP_ADMINS=Starefossen,kvikshaug
      - DEV_DB=ntbdev

  redis:
    image: redis:3
    network_mode: 'bridge'

  mongo:
    image: mongo:3.0
    network_mode: 'bridge'
